#!/usr/bin/ruby -w
# $Id$

require 'optparse'
require 'rdoc/usage'
require 'mysql'

DEBUG       = false
REDTEXT     = "\033[31m"
GREENTEXT   = "\033[32m"
YELLOWTEXT  = "\033[33m"
BLUETEXT    = "\033[34m"
VIOLETTEXT  = "\033[35m"
CYANTEXT    = "\033[36m"
GREYTEXT    = "\033[37m"
NORMALTEXT  = "\033[0m"

HOST        = "localhost"
USER        = ENV['USER']
PASSWORD    = "b1gkzxuSCW8yw"
DB          = "journal"

begin

    # connect to the MySQL server
    dbh = Mysql.real_connect(HOST, USER, PASSWORD, DB)

    # If no arguments launch vim. The contents of the file are then loaded to
    # the table.
    if ARGV.empty?
        qstr = "LOAD DATA LOCAL INFILE "
        qstr2 = "INTO TABLE entry LINES TERMINATED BY \'\' (text)"
        tmpfile = `mktemp /tmp/journal.XXXXXX`
        tmpfile.chomp!
        system("vi \'+set tw=80\' #{tmpfile}")
        qstr = qstr + "\'#{tmpfile}\' " + qstr2
        if DEBUG
            puts qstr
        end
        dbh.query("#{qstr}")
        system("rm #{tmpfile}")

    elsif ARGV[0] == "-s"
        # search for text using regular expression
        qstr = "SELECT * FROM entry WHERE text REGEXP \'#{ARGV[1]}\'"
        if DEBUG
            puts qstr
        end
        res = dbh.query("#{qstr}")

        res.each_hash do |row|
            printf GREENTEXT + "%s " + NORMALTEXT + "\n%s\n", 
                row['entrydate'], row['text']
        end
        res.free
    else
        # All others assume entry is from command line MUST be quoted.
        qstr = "INSERT INTO entry (text) VALUES "
        qstr = qstr + "(\"#{ARGV}\")"
        if DEBUG
            puts qstr
        end
        dbh.query("#{qstr}")
    end

rescue Mysql::Error => e
    puts "Error code: #{e.errno}"
    puts "Error message: #{e.error}"
    puts "Error SQLSTATE: #{e.sqlstate}" if e.respond_to?("sqlstate")
ensure
    # disconnect from server
    dbh.close if dbh
end

